### ISSUE TITLE
Staff page tweaks

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#10] opened 2015-10-02 15:49 UTC
- Add job titles to each person on the staff page
- Ability to customize order? Or sort alphabetically by last name?

**Comment by devansart** [comment] 2015-10-02 16:32
Customized order is preferred here.

**Comment by sethrubenstein** [comment] 2015-10-05 17:26
Lets do manual sorting of bylines.

**Comment by sethrubenstein** [comment] 2015-10-06 01:09
Closed as duplicated of #5

**Comment by devansart** [comment] 2015-10-07 13:52
The list of staff on the About page are to the old bio pages (author). How do we get the new versions (person) with the latest  work included to show up here. I tried adding them in the drag and drop window but they don't show up anywhere. And I am assuming you'll need to get rid of the old one (author) too? Related: The old version (author) has a Download a hi-res photo link built into the photo. If you look at my new bio page (http://equitablegrowth.org/person/david-evans/) the hi-res photo does not work.

**Comment by sethrubenstein** [comment] 2015-10-07 13:55
Hey @devansart thatll be possible hopefully this evening when I finish up the new staff page tonight. I'm closing this particular ticket because its a duplicate of #5

**Closed by sethrubenstein** 2015-10-07 13:55 UTC
Labels: cap-byline
