### ISSUE TITLE
Block quote style adjustment

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#44] opened 2015-10-21 16:08 UTC
Attached is a before and after of how we'd like to change the style on block quotes. Brad's long block quotes have brought this up as a needed area of improvement.

**Before**
![screen shot 2015-10-21 at 12 06 21 pm](https://cloud.githubusercontent.com/assets/14931609/10642572/55b9b6ee-77ec-11e5-9902-8eac27afbd60.png)

**After**
![blockquote](https://cloud.githubusercontent.com/assets/14931609/10642511/0d8316f4-77ec-11e5-8c92-8bf1ee74bc2e.png)
Notice the vertical bar is closer to the quoted text. And the text hex color is changed to #555555

**Comment by sethrubenstein** [comment] 2015-11-29 00:07
Duplicate of #54

**Closed** 2015-12-05 04:38 UTC
Labels: duplicate
